# Generated by Django 5.2.6 on 2025-10-21 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 21, 5, 10, 11, 362184, tzinfo=datetime.timezone.utc)),
        ),
    ]
