# Generated by Django 5.2.6 on 2025-09-28 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='preview')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='preview')),
                ('description', models.TextField()),
                ('link_video', models.URLField()),
                ('course', models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='materials.course')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ['name'],
            },
        ),
    ]
