# Generated by Django 5.2.6 on 2025-10-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_notified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
